name: bump-versions
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: The new version (without -SNAPSHOT)
        required: true
        type: string

jobs:
  bump-version:
    runs-on: sonar-xs
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - env:
          VERSION: "${{ inputs.version }}-SNAPSHOT"
        run: |
          sed -i "s/version=.*-SNAPSHOT/version=${VERSION}/" gradle.properties
      - uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          author: ${{ github.actor }} <${{ github.actor }}>
          commit-message: Prepare next development iteration
          title: "Prepare next development iteration ${{ inputs.version }}"
          branch: bot/bump-project-version
          branch-suffix: timestamp
          base: master
          reviewers: ${{ github.actor }}
